[[redirects]]
  from = "http://localhost:3000/"
  to = "https://codesquad-comics-server.netlify.app"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"